import type { DashboardOrder, Product, ProductCategory, WorkflowStepBlueprint } from "@/lib/types";

export const categoryOrder: ProductCategory[] = ["sets", "vestidos", "denim", "accesorios"];

export const products: Product[] = [
  {
    id: "look-atelier-01",
    slug: "set-atelier-marfil",
    name: "Set Atelier Marfil",
    category: "sets",
    categoryLabel: "Sets curados",
    priceCop: 389000,
    saleMode: "immediate",
    paymentPolicy: "full_today",
    badge: "Mas vendido",
    leadTimeLabel: "Entrega inmediata en Colombia",
    description: "Conjunto fluido con silueta relajada y terminados limpios para uso diario elevado.",
    story: "Pensado para clientas que quieren verse pulidas sin sentir el look demasiado armado.",
    materialNote: "Lino mezcla de tacto seco y caida elegante.",
    sizes: ["S", "M", "L"],
    featured: true,
  },
  {
    id: "look-atelier-02",
    slug: "vestido-noir-galeria",
    name: "Vestido Noir Galeria",
    category: "vestidos",
    categoryLabel: "Vestidos con historia",
    priceCop: 459000,
    saleMode: "preorder",
    paymentPolicy: "split_50_50",
    badge: "Edicion limitada",
    leadTimeLabel: "Llegada estimada en 12 a 18 dias",
    description: "Vestido negro de linea larga con espalda limpia y movimiento suave.",
    story: "Una pieza de impacto sereno para cenas, eventos y armario capsula.",
    materialNote: "Satin mate con brillo controlado.",
    sizes: ["XS", "S", "M"],
    featured: true,
  },
  {
    id: "look-atelier-03",
    slug: "denim-porto-recto",
    name: "Denim Porto Recto",
    category: "denim",
    categoryLabel: "Denim refinado",
    priceCop: 279000,
    saleMode: "immediate",
    paymentPolicy: "full_today",
    badge: "Reposicion",
    leadTimeLabel: "Stock listo para despacho",
    description: "Jean recto de tiro alto con lavado profundo y horma favorecedora.",
    story: "Un basico con intencion para elevar camisas, blazers y tops de noche.",
    materialNote: "Denim premium con estructura media.",
    sizes: ["6", "8", "10", "12"],
    featured: true,
  },
  {
    id: "look-atelier-04",
    slug: "bolso-roma-onyx",
    name: "Bolso Roma Onyx",
    category: "accesorios",
    categoryLabel: "Accesorios clave",
    priceCop: 329000,
    saleMode: "preorder",
    paymentPolicy: "split_50_50",
    badge: "Por encargo",
    leadTimeLabel: "Importacion curada por FerShop",
    description: "Bolso estructurado de presencia limpia para elevar looks de oficina y viaje.",
    story: "Ideal para clientas que compran pocas piezas, pero muy pensadas.",
    materialNote: "Cuero vegano texturizado con herrajes oscuros.",
    sizes: ["Unica"],
    featured: true,
  },
  {
    id: "look-atelier-05",
    slug: "set-luna-piedra",
    name: "Set Luna Piedra",
    category: "sets",
    categoryLabel: "Sets curados",
    priceCop: 409000,
    saleMode: "preorder",
    paymentPolicy: "split_50_50",
    badge: "Nueva seleccion",
    leadTimeLabel: "Disponible bajo pedido",
    description: "Top y falda coordinados con textura sutil y look editorial.",
    story: "Una propuesta para clientas que quieren algo especial sin perder versatilidad.",
    materialNote: "Tejido texturizado con forro suave.",
    sizes: ["S", "M"],
  },
  {
    id: "look-atelier-06",
    slug: "vestido-riviera-crema",
    name: "Vestido Riviera Crema",
    category: "vestidos",
    categoryLabel: "Vestidos con historia",
    priceCop: 498000,
    saleMode: "immediate",
    paymentPolicy: "full_today",
    badge: "Pocas unidades",
    leadTimeLabel: "Listo para entrega inmediata",
    description: "Vestido largo con escote limpio y presencia sofisticada.",
    story: "Disenado para verano, resort y celebraciones pequenas con aire premium.",
    materialNote: "Viscosa premium con caida ligera.",
    sizes: ["S", "M"],
  },
  {
    id: "look-atelier-07",
    slug: "denim-viena-oscuro",
    name: "Denim Viena Oscuro",
    category: "denim",
    categoryLabel: "Denim refinado",
    priceCop: 319000,
    saleMode: "preorder",
    paymentPolicy: "split_50_50",
    badge: "Vuelve pronto",
    leadTimeLabel: "Llega a Colombia en la siguiente importacion",
    description: "Silueta barrel pulida para looks de tendencia con balance comercial.",
    story: "Una referencia con imagen fuerte para contenido, vitrinas y clientas fashion aware.",
    materialNote: "Denim con estructura firme y lavado oscuro.",
    sizes: ["6", "8", "10"],
  },
  {
    id: "look-atelier-08",
    slug: "cartera-siena-hueso",
    name: "Cartera Siena Hueso",
    category: "accesorios",
    categoryLabel: "Accesorios clave",
    priceCop: 289000,
    saleMode: "immediate",
    paymentPolicy: "full_today",
    badge: "Favorito FerShop",
    leadTimeLabel: "Despacho el mismo dia habil",
    description: "Cartera compacta para looks de dia y noche con acabado limpio.",
    story: "Una pieza pensada para clientas que buscan pulcritud visual y funcionalidad.",
    materialNote: "Acabado liso con estructura firme.",
    sizes: ["Unica"],
  },
];

export const workflowBlueprint: WorkflowStepBlueprint[] = [
  {
    key: "pedido-recibido",
    title: "Pedido recibido",
    owner: "Comercial",
    triggerLabel: "La clienta confirma la referencia",
    description:
      "Se crea el pedido con la forma de venta correcta y queda claro cuanto se cobra hoy y cuanto queda pendiente.",
  },
  {
    key: "anticipo-registrado",
    title: "Anticipo registrado",
    owner: "Caja",
    triggerLabel: "Se confirma pago inicial o pago completo",
    description:
      "FerShop registra el anticipo real, actualiza caja y deja trazado si la compra puede pasar a origen.",
  },
  {
    key: "compra-realizada",
    title: "Compra realizada en origen",
    owner: "Operaciones",
    triggerLabel: "El pedido ya puede comprarse",
    description:
      "Se confirma compra internacional, se actualiza el pedido y se notifica a la clienta que su referencia ya fue comprada.",
  },
  {
    key: "llegada-colombia",
    title: "Llegada a Colombia",
    owner: "Operaciones",
    triggerLabel: "La mercancia llega al pais",
    description:
      "El sistema marca llegada, habilita cobro de saldo y dispara el mensaje de segundo pago cuando aplique.",
  },
  {
    key: "segundo-pago",
    title: "Segundo pago confirmado",
    owner: "Caja",
    triggerLabel: "La clienta paga el saldo",
    description:
      "Se registra el segundo pago, se deja el pedido listo para entrega y se envia confirmacion a la clienta.",
  },
  {
    key: "entrega",
    title: "Entrega y cierre",
    owner: "Servicio",
    triggerLabel: "Se agenda o despacha la entrega",
    description:
      "El pedido pasa a entrega, se comparte el ultimo mensaje de seguimiento y el caso queda cerrado.",
  },
];

export const dashboardOrders: DashboardOrder[] = [];
